mg-*: Make Debian package fetching common in mgi-common
This pattern appears several times in mg-debian-installer-update and
I'm about to add another script which uses it.

The centralised version always does "sort -n -r | head -n" to pick out
only the newest version, which only some of the open coded sites did.

Likewise the centralised version checks that $pkgfile is non-empty,
unlike some of the open coded sites.

Signed-off-by: Ian Campbell <ian.campbell@citrix.com>
Acked-by: Ian Jackson <ian.jackson@eu.citrix.com>

---
v4: Fold into mgi-common instead
v3: New patch

diff --git a/mgi-common b/mgi-common
--- a/mgi-common
+++ b/mgi-common
@@ -24,3 +24,22 @@ fetch () {
 	# no-cache due to intercepting proxies messing things up.
 	curl -s -H 'Pragma: no-cache' $1
 }
+
+# Arguments: <Base URL> <Packages.gz> <grep-dctrl arguments>
+#
+# nb: -nsFilename argument to grep-dctrl is supplied here
+fetch_debian_package () {
+    local site=$1 ; shift 1
+    local pgz=$1 ; shift 1
+
+    set +e
+    pkgfile=`zcat $pgz | grep-dctrl $@ -nsFilename | sort -n -r | head -n1`
+    rc=$?
+    set -e
+
+    if [ $rc -ne 0 ] || [ x$pkgfile = x ]; then
+	fail "package matching $@ not found";
+    fi
+
+    fetch "$site/$pkgfile"
+}
