standalone: Use WebspaceLog for apache log check
Also print the result in the error message for cut-and-paste convenience.

While there I noticed that run-test was setting OSSTEST_CONFIG twice.

Signed-off-by: Ian Campbell <ian.campbell@citrix.com>
Acked-by: Ian Jackson <ian.jackson@eu.citrix.com>

diff --git a/standalone b/standalone
--- a/standalone
+++ b/standalone
@@ -78,8 +78,11 @@ while true ; do
     esac
 done
 
-if [ ! -r /var/log/apache2/access.log ] ; then
-    echo "WARNING: Cannot read apache logs. Some tests may fail" >&2
+. cri-getconfig
+
+WebspaceLog=`OSSTEST_CONFIG=$config getconfig WebspaceLog`
+if [ ! -r "$WebspaceLog" ] ; then
+    echo "WARNING: Cannot read apache logs at $WebspaceLog. Some tests may fail" >&2
 fi
 
 if ! ssh-add -l >/dev/null ] ; then
@@ -222,7 +225,6 @@ case $op in
 
 	OSSTEST_CONFIG=$config \
 	OSSTEST_FLIGHT=$flight \
-	OSSTEST_CONFIG=$config \
 	OSSTEST_HOST_REUSE=$reuse \
 	OSSTEST_JOB=$job \
 	    with_logging logs/$flight/$job.$ts.log ./$ts host=$host $@
