standalone: force an explicit default config
Some scripts (e.g. cri-args-hostlists) default to production-config instead of
the more expected ~/.xen-osstest/config. I keep forgetting this, so set the
more appropriate default in the helper script.

Signed-off-by: Ian Campbell <ian.campbell@citrix.com>
Acked-by: Ian Jackson <ian.jackson@eu.citrix.com>

diff --git a/standalone b/standalone
--- a/standalone
+++ b/standalone
@@ -59,7 +59,7 @@ TEMP=$(getopt -o c:f:h:rR --long config:,flight:,host:,reuse,noreuse,reinstall,h
 
 eval set -- "$TEMP"
 
-config=
+config=$HOME/.xen-osstest/config
 flight="standalone"
 host=
 reuse=1 # Don't blow away machines by default
@@ -94,6 +94,11 @@ fi
 
 if [ ! -f standalone.db ] ; then
     echo "No standalone.db? Run standalone-reset." >&2
+    exit 1
+fi
+
+if [ -z "$config" -o ! -r "$config" ] ; then
+    echo "Cannot read config." >&2
     exit 1
 fi
 
